version: "3.8"

services:

  sql_db_caleb:
    build: ./sql_db_caleb
    container_name: sql_db_caleb
    expose:
      - 3306
    volumes:
      - db_data_caleb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD
    networks: 
      nginx_proxy_network:
        aliases: 
          - sql_db_caleb
      
        
  wordpress_caleb:
    depends_on:
      - sql_db_caleb
    build: ./wordpress_caleb
    container_name: wordpress_caleb
    ports:
      - 80
    restart: always
    volumes: ['wordpress_caleb_data:/var/www/html']
    environment:
      SERVER_NAME: calebhuck.me
      WORDPRESS_DB_HOST: sql_db_caleb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
      WORDPRESS_DB_NAME: wordpress
    networks: 
      nginx_proxy_network:
        aliases: 
          - wordpress_caleb


  sql_db_sam:
    build: ./sql_db_sam
    container_name: sql_db_sam
    ports:
      - "3306:3306"
    volumes:
      - db_data_sam:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: PASSWORD
    networks: 
      nginx_proxy_network:
        aliases: 
          - sql_db_sam
      
       
  wordpress_sam:
    depends_on:
      - sql_db_sam
    build: ./wordpress_sam
    container_name: wordpress_sam
    ports:
      - 80
    restart: always
    volumes: ['wordpress_sam_data:/var/www/html']
    environment:
      SERVER_NAME: atthetable.community
      WORDPRESS_DB_HOST: sql_db_sam:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
      WORDPRESS_DB_NAME: wordpress
    networks:
      nginx_proxy_network:
        aliases: 
          - wordpress_sam

  #phpmyadmin:
  #  build: ./phpmyadmin
  #  container_name: phpmyadmin
  #  environment:
  #    - PMA_HOST=sql_db_caleb
  #    - PMA_PORT=3306
  #    - PMA_USER=wordpress
  #    - PMA_PASSWORD=PASSWORD
  #    - PMA_ABSOLUTE_URI=http://phpmyadmin.calebhuck.me/
  #  restart: always
  #  ports:
  #    - 80
  #  volumes: ['phpmyadmin_data:/sessions']
  #  networks:
  #    nginx_proxy_network:
  #      aliases: 
  #        - pypmyadmin

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      nginx_proxy_network:
        aliases: 
          - nginx-proxy

  dns_updater:
    build: ./DNS_Updater
    container_name: DNS_Updater
    restart: always
  
  cloudflare_updater:
    build: ./Cloudflare_Updater
    container_name: Cloudflare_Updater
    restart: always
    
  #pihole:
  #  container_name: pihole
  #  image: pihole/pihole:latest
  #  ports:
  #    - "53/tcp"
  #    - "53/udp"
  #    - "67/udp"
  #    - "80/tcp"
  #    - "443/tcp"
  #  environment:
  #    TZ: 'America/Chicago'
  #    WEBPASSWORD: 'password'
  #  volumes:
  #    - 'pihole_data:/etc/pihole/'
  #    - 'pihole_dns_masq:/etc/dnsmasq.d/'
  #  # Recommended but not required (DHCP needs NET_ADMIN)
  #  #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #  cap_add:
  #    - NET_ADMIN
  #  restart: unless-stopped
  #  networks:
  #    nginx_proxy_network:
  #      aliases: 
  #        - pihole


networks:
  nginx_proxy_network:
    name: nginx_proxy_network


volumes:
  #sam's wordpress site db and site data
  db_data_sam:
    driver: local
    name: db_data_sam
  wordpress_sam_data:
    driver: local
    name: wordpress_sam_data

  #caleb's wordpress site db and site data
  db_data_caleb:
    driver: local
    name: db_data_caleb
  wordpress_caleb_data:
    driver: local
    name: wordpress_caleb_data

  #pypmyadmin session data
  phpmyadmin_data:
    driver: local
    name: pypmyadmin_data

  #pihole data
  pihole_data:
    driver: local
    name: pihole_data
  pihole_dns_masq:
    driver: local
    name: pihole_dns_masq